const PHASE_CATEGORY = {
  teardown: 'body',
  body: 'body',
  paint_prep: 'paint',
  paint: 'paint',
  reassembly: 'body',
  sublet: 'sublet',
  detail: 'detail',
}

const PHASE_TITLE_PATTERN = {
  teardown: /teardown/i,
  body: /body work|repair/i,
  paint_prep: /paint.?prep|prep/i,
  paint: /paint/i,
  reassembly: /reassembl/i,
  sublet: /sublet/i,
  detail: /detail|qc/i,
}

const PRIMARY_PHASES = new Set(['teardown', 'body', 'paint_prep', 'paint', 'reassembly'])

function normalizeSemanticTitle(value = '') {
  return String(value)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim()
}

function normalizeAssigneeText(value = '') {
  return String(value)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim()
}

export function actionHasExplicitAssigneeIntent(action = {}, inputText = '', assignee = null, employees = []) {
  if (action.assigneeUserEdited === true) return true
  if (action.autoGenerated || !assignee?.name) return false

  const normalizedInput = ` ${normalizeAssigneeText(inputText)} `
  const actionName = normalizeAssigneeText(action.assigneeName)
  if (actionName && normalizedInput.includes(` ${actionName} `)) return true

  const employeeList = Array.isArray(employees) ? employees : []
  const assigneeParts = normalizeAssigneeText(assignee.name).split(' ').filter(Boolean)
  return assigneeParts.some(part => (
    normalizedInput.includes(` ${part} `)
    && employeeList.filter(employee => (
      normalizeAssigneeText(employee.name).split(' ').filter(Boolean).includes(part)
    )).length === 1
  ))
}

export function gibTaskSemanticKey(task = {}) {
  if (typeof task.gibSemanticKey === 'string' && task.gibSemanticKey.trim()) {
    return task.gibSemanticKey.trim()
  }
  if (!task.phase || task.taskKind === 'secondary') return ''
  if (
    task.taskKind === 'primary'
    || (PRIMARY_PHASES.has(task.phase) && (task.autoTriggered === true || task.source === 'auto'))
  ) {
    return `primary:${task.phase}`
  }
  if (task.autoTriggered === true || task.source === 'auto') {
    const title = normalizeSemanticTitle(task.title)
    return title ? `auto:${task.phase}:${title}` : ''
  }
  return ''
}

export function hasOpenTaskForSemanticKey(items = [], taskUpdates, candidate = {}) {
  const candidateKey = gibTaskSemanticKey(candidate)
  if (!candidateKey) return false
  return items.some(item => {
    const task = item.isNew
      ? item.data
      : { ...item.data, ...(taskUpdates?.get(item.ref.path)?.fields || {}) }
    return task.status !== 'completed' && gibTaskSemanticKey(task) === candidateKey
  })
}

export function phaseIsCompleteAtStatus(phase, status) {
  const completedByStatus = {
    waiting_parts: ['teardown'],
    body_work: ['teardown', 'waiting_parts'],
    body_complete: ['teardown', 'waiting_parts', 'body'],
    paint_prep: ['teardown', 'waiting_parts', 'body'],
    in_paint: ['teardown', 'waiting_parts', 'body', 'paint_prep'],
    paint_complete: ['teardown', 'waiting_parts', 'body', 'paint_prep', 'paint'],
    reassembly: ['teardown', 'waiting_parts', 'body', 'paint_prep', 'paint'],
    sublet: ['teardown', 'waiting_parts', 'body', 'paint_prep', 'paint', 'reassembly'],
    detail: ['teardown', 'waiting_parts', 'body', 'paint_prep', 'paint', 'reassembly', 'sublet'],
    ready: ['teardown', 'waiting_parts', 'body', 'paint_prep', 'paint', 'reassembly', 'sublet', 'detail'],
    total_loss: ['teardown', 'waiting_parts', 'body', 'paint_prep', 'paint', 'reassembly', 'sublet', 'detail'],
    delivered: ['teardown', 'waiting_parts', 'body', 'paint_prep', 'paint', 'reassembly', 'sublet', 'detail'],
  }
  return (completedByStatus[status] || []).includes(phase)
}

export function taskMatchesOpenTemplate(task = {}, template = {}) {
  if (!template.phase || task.phase !== template.phase) return false
  const isPaintPrimary = template.category === 'paint' && template.taskKind === 'primary'
  if (isPaintPrimary) {
    return task.taskKind !== 'secondary'
      && (template.statusBackfill || task.status !== 'completed')
  }
  return task.status !== 'completed' && task.title === template.title
}

export function selectPendingPhaseTaskItems(items = [], phase, getTaskData = item => item.data) {
  const phaseMatches = items.filter(item => {
    const task = getTaskData(item)
    return task.phase === phase && task.status !== 'completed'
  })
  if (phaseMatches.length > 0) return phaseMatches

  const category = PHASE_CATEGORY[phase]
  const titlePattern = PHASE_TITLE_PATTERN[phase]
  if (!category) return []
  return items.filter(item => {
    const task = getTaskData(item)
    return task.status !== 'completed'
      && task.category === category
      && (!titlePattern || titlePattern.test(task.title ?? ''))
  })
}
