import test from 'node:test'
import assert from 'node:assert/strict'
import {
  actionHasExplicitAssigneeIntent,
  gibTaskSemanticKey,
  hasOpenTaskForSemanticKey,
  phaseIsCompleteAtStatus,
  selectPendingPhaseTaskItems,
  taskMatchesOpenTemplate,
} from './gibTaskPlanning.js'

test('assignee intent accepts explicit unique first names but rejects automatic defaults', () => {
  const employees = [
    { uid: 'gustavo', name: 'Gustavo Montes', role: 'painter' },
    { uid: 'alice', name: 'Alice Rivera', role: 'painter' },
  ]
  const gustavo = employees[0]
  assert.equal(actionHasExplicitAssigneeIntent(
    { type: 'assign_painter', assigneeName: 'Gustavo Montes' },
    'assign painter Gustavo',
    gustavo,
    employees,
  ), true)
  assert.equal(actionHasExplicitAssigneeIntent(
    { type: 'assign_task', assigneeName: 'Gustavo Montes', autoGenerated: true },
    'move RO to paint prep',
    gustavo,
    employees,
  ), false)
  assert.equal(actionHasExplicitAssigneeIntent(
    { type: 'assign_task', assigneeName: 'Gustavo Montes', assigneeUserEdited: true, autoGenerated: true },
    'move RO to paint prep',
    gustavo,
    employees,
  ), true)
  assert.equal(actionHasExplicitAssigneeIntent(
    { type: 'assign_painter', assigneeName: 'Gustavo Montes' },
    'assign painter Gustavo',
    gustavo,
    [...employees, { uid: 'other-gustavo', name: 'Gustavo Diaz', role: 'paint_helper' }],
  ), false)
})

test('open-template matching ignores completed and secondary paint tasks', () => {
  const template = { title: 'Paint', phase: 'paint', category: 'paint', taskKind: 'primary' }
  assert.equal(taskMatchesOpenTemplate({ title: 'Paint', phase: 'paint', status: 'pending', taskKind: 'primary' }, template), true)
  assert.equal(taskMatchesOpenTemplate({ title: 'Paint', phase: 'paint', status: 'completed', taskKind: 'primary' }, template), false)
  assert.equal(taskMatchesOpenTemplate({ title: 'Paint reminder', phase: 'paint', status: 'pending', taskKind: 'secondary' }, template), false)
})

test('phase completion selects all pending tasks with the exact phase', () => {
  const items = [
    { id: 'primary', data: { phase: 'body', category: 'body', title: 'Repair', status: 'pending' } },
    { id: 'secondary', data: { phase: 'body', category: 'body', title: 'Fitment Check', status: 'in_progress' } },
    { id: 'done', data: { phase: 'body', category: 'body', title: 'Repair', status: 'completed' } },
    { id: 'other', data: { phase: 'paint', category: 'paint', title: 'Paint', status: 'pending' } },
  ]
  assert.deepEqual(selectPendingPhaseTaskItems(items, 'body').map(item => item.id), ['primary', 'secondary'])
})

test('phase completion uses legacy category and title fallback only when no exact phase is pending', () => {
  const items = [
    { id: 'legacy-repair', data: { category: 'body', title: 'Body Work', status: 'pending' } },
    { id: 'legacy-unrelated', data: { category: 'body', title: 'Tire Pressure Check', status: 'pending' } },
    { id: 'completed-phase', data: { phase: 'body', category: 'body', title: 'Repair', status: 'completed' } },
  ]
  assert.deepEqual(selectPendingPhaseTaskItems(items, 'body').map(item => item.id), ['legacy-repair'])
})

test('phase selection honors effective planned task state', () => {
  const items = [
    { id: 'planned-done', data: { phase: 'paint_prep', category: 'paint', title: 'Paint Prep', status: 'pending' } },
    { id: 'still-open', data: { phase: 'paint_prep', category: 'paint', title: 'Prep reminder', status: 'pending' } },
  ]
  const effective = item => item.id === 'planned-done' ? { ...item.data, status: 'completed' } : item.data
  assert.deepEqual(selectPendingPhaseTaskItems(items, 'paint_prep', effective).map(item => item.id), ['still-open'])
})

test('final phase completion is independent of task-versus-completion action order', () => {
  const selectedIds = steps => {
    const items = []
    let completionRequested = false
    steps.forEach(step => {
      if (step === 'task') items.push({ id: 'repair', data: { phase: 'body', category: 'body', title: 'Repair', status: 'pending' } })
      if (step === 'complete') completionRequested = true
    })
    return completionRequested
      ? selectPendingPhaseTaskItems(items, 'body').map(item => item.id)
      : []
  }
  assert.deepEqual(selectedIds(['task', 'complete']), ['repair'])
  assert.deepEqual(selectedIds(['complete', 'task']), ['repair'])
})

test('singleton task keys unify downstream and explicit primary tasks', () => {
  assert.equal(gibTaskSemanticKey({ phase: 'body', title: 'Repair', source: 'auto', autoTriggered: true }), 'primary:body')
  assert.equal(gibTaskSemanticKey({ phase: 'body', title: 'Body Work', taskKind: 'primary', source: 'gib' }), 'primary:body')
  assert.equal(gibTaskSemanticKey({ phase: 'paint', title: 'Paint', taskKind: 'primary' }), 'primary:paint')
  assert.equal(gibTaskSemanticKey({ phase: 'detail', title: 'QC inspection', source: 'auto', autoTriggered: true }), 'auto:detail:qc inspection')
  assert.equal(gibTaskSemanticKey({ phase: 'body', title: 'Fitment Check', taskKind: 'secondary' }), '')
})

test('semantic matching ignores completed singleton tasks and preserves reminders', () => {
  const items = [
    { ref: { path: 'tasks/repair' }, data: { phase: 'body', title: 'Repair', source: 'auto', autoTriggered: true, status: 'pending' } },
    { ref: { path: 'tasks/done' }, data: { phase: 'paint', title: 'Paint', taskKind: 'primary', status: 'completed' } },
  ]
  assert.equal(hasOpenTaskForSemanticKey(items, new Map(), { phase: 'body', title: 'Body Work', taskKind: 'primary' }), true)
  assert.equal(hasOpenTaskForSemanticKey(items, new Map(), { phase: 'paint', title: 'Paint', taskKind: 'primary' }), false)
  assert.equal(hasOpenTaskForSemanticKey(items, new Map(), { phase: 'body', title: 'Call customer', taskKind: 'secondary' }), false)
})

test('old primary phases are suppressed after the RO advances', () => {
  assert.equal(phaseIsCompleteAtStatus('body', 'paint_prep'), true)
  assert.equal(phaseIsCompleteAtStatus('paint', 'in_paint'), false)
  assert.equal(phaseIsCompleteAtStatus('reassembly', 'detail'), true)
})
